### ISSUE TITLE
Inconsistencies in <tag id="lowerCamelCase"> vs <tag id = "snake_case"> should be refactored to match existing naming strategy.

### ISSUE THREAD

**Issue by smdupor** [smdupor/expertiza#8]

**Comment by BrightReach** [comment]
Looking at fixing the issue. Anywhere in particular I'll need to look into for inconsistencies? Also, the naming strategy is Snake Case, if I'm correct?

**Comment by smdupor** [comment]
Hey Craig, this repo is a small  group working on the much larger research project Expertiza at North Carolina State University, NC, US. Since this work is related to academic credit, we unfortunately aren't able to accept external contributions to this repo.  If you're interested in the broader Expertiza project / the research, etc, you should check out the main project at [Expertiza/expertiza](https://github.com/expertiza/expertiza).

**Comment by JialinC** [comment]
@smdupor Hi Steven, I find the place where the <tag id = "snake_case"> is generated. So there is a class/model called TagPrompt in app/models/tag_prompt.rb, where each tag is generated as:

element_id = answer.id.to_s + '_' + self.id.to_s
control_id = "tag_prompt_" + element_id

This model also generated other tags in this format, I could of course try to refactor this model, but since it is a model existing there not only for the issue that we are working on but also potentially used by others, do you think we should still refactor this? Thanks.

**Comment by JialinC** [comment]
I also think they may make this in snake case on purpose, since those element_id has some meanings regarding to answer model and user, probably could be used to locate a database item.

**Comment by smdupor** [comment]
Refactor was completed two weeks ago. Closing.
